- repo: https://github.com/GitGuardian/ggshield
  rev: v1.25.0  # 最新バージョンを指定
  hooks:
    - id: ggshield

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.7.0  # 最新安定版を指定
  hooks:
    - id: autopep8
      args: [--max-line-length=120]
