name: GitGuardian scan

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  merge_group:

permissions:
  contents: read

jobs:
  scan:
    name: GitGuardian Scan  # ←これを追加！
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
